/**
 * Common Magic Items from Warhammer: The Old World.
 *
 * Each item has:
 *   name        – canonical name
 *   type        – weapon | armour | talisman | arcane-item | enchanted-item | banner
 *   points      – points cost
 *   effect      – full rules text
 *   phases      – array of phase IDs where the item is relevant (matches phases.js)
 *                 'combat' | 'shooting' | 'movement' | 'strategy' | 'passive'
 *   subPhases   – optional array of sub-phase IDs for finer filtering (matches phases.js)
 *                 when set, the item only shows in those specific sub-phases
 *                 when absent, the item shows in all sub-phases of its phase(s)
 *   extremely   – true if the item is an "Extremely Common" magic item (no duplicate limit)
 *
 * Source: https://tow.whfb.app/magic-items
 */

export const MAGIC_ITEMS = [
  // ─── Magic Weapons ──────────────────────────────────────────────────
  {
    name: 'Ogre Blade',
    type: 'weapon',
    points: 75,
    effect: 'S+2, -2 AP. Armour Bane (1), Magical Attacks, Multiple Wounds (D3).',
    phases: ['combat'],
  },
  {
    name: 'Cackling Blade',
    type: 'weapon',
    points: 65,
    effect: 'S+1, -1 AP. Extra Attacks (+D6), Magical Attacks. If a natural 6 is rolled for the Extra Attacks (+D6) special rule, the wielder immediately loses a single Wound.',
    phases: ['combat'],
  },
  {
    name: 'Sword of Battle',
    type: 'weapon',
    points: 60,
    effect: 'S+1, -1 AP. Armour Bane (1), Extra Attacks (+1), Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: "Duellist's Blades",
    type: 'weapon',
    points: 55,
    effect: 'S, -1 AP. Extra Attacks (+2), Magical Attacks, Requires Two Hands.',
    phases: ['combat'],
  },
  {
    name: 'Dragon Slaying Sword',
    type: 'weapon',
    points: 50,
    effect: 'S, no AP. Magical Attacks, Monster Slayer.',
    phases: ['combat'],
  },
  {
    name: 'Meteor Hammer',
    type: 'weapon',
    points: 50,
    effect: 'S, -3 AP. Magical Attacks, Requires Two Hands. When making a roll To Wound with this weapon, a roll of 3+ is always a success, regardless of the target\'s Toughness.',
    phases: ['combat'],
  },
  {
    name: "Headsman's Axe",
    type: 'weapon',
    points: 45,
    effect: 'S+1, -1 AP. Killing Blow, Magical Attacks, Requires Two Hands.',
    phases: ['combat'],
  },
  {
    name: 'Spelleater Axe',
    type: 'weapon',
    points: 35,
    effect: 'S, -1 AP. Magical Attacks, Magic Resistance (-2).',
    phases: ['combat', 'strategy'],
    subPhases: ['combat'],
  },
  {
    name: 'Giant Blade',
    type: 'weapon',
    points: 30,
    effect: 'S+1, no AP. Armour Bane (2), Magical Attacks, Multiple Wounds (2).',
    phases: ['combat'],
  },
  {
    name: 'Hell-forged Axe',
    type: 'weapon',
    points: 30,
    effect: 'S+1, -1 AP. Armour Bane (3), Flaming Attacks, Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Sword of Sorrow',
    type: 'weapon',
    points: 30,
    effect: 'Range 30", Strength 5, -1 AP. Armour Bane (2), Magical Attacks, Multiple Wounds (2). Missile weapon only; cannot be used in combat. No Ward or Regeneration saves permitted against wounds caused.',
    phases: ['shooting'],
  },
  {
    name: 'Sword of Swiftness',
    type: 'weapon',
    points: 25,
    effect: 'S, no AP. Magical Attacks, Strike First.',
    phases: ['combat'],
  },
  {
    name: 'Berserker Blade',
    type: 'weapon',
    points: 20,
    effect: 'S+1, no AP. Extra Attacks (+1), Impetuous, Magical Attacks.',
    phases: ['combat', 'movement'],
    extremely: true,
  },
  {
    name: 'Sword of Might',
    type: 'weapon',
    points: 20,
    effect: 'S+1, -1 AP. Magical Attacks.',
    phases: ['combat'],
    extremely: true,
  },
  {
    name: 'Biting Blade',
    type: 'weapon',
    points: 15,
    effect: 'S, -2 AP. Armour Bane (1), Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Sword of Striking',
    type: 'weapon',
    points: 15,
    effect: 'S, no AP. Magical Attacks. During the Combat phase, the wielder has a +1 modifier to their rolls To Hit.',
    phases: ['combat'],
    extremely: true,
  },
  {
    name: 'Burning Blade',
    type: 'weapon',
    points: 5,
    effect: 'S, no AP. Flaming Attacks, Magical Attacks.',
    phases: ['combat'],
    extremely: true,
  },

  // ─── Magic Armour ───────────────────────────────────────────────────
  {
    name: 'Armour of Destiny',
    type: 'armour',
    points: 70,
    effect: 'Heavy armour. The wearer has a 4+ Ward save against any wounds suffered.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Bedazzling Helm',
    type: 'armour',
    points: 60,
    effect: 'Infantry or cavalry only. May be worn with other armour. Improves armour value by 1 (max 2+). Any enemy model directing attacks against the wearer during the Combat phase suffers -1 To Hit.',
    phases: ['combat'],
  },
  {
    name: 'Armour of Silvered Steel',
    type: 'armour',
    points: 40,
    effect: 'Gives the wearer an armour value of 3+ which cannot be improved in any way.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Glittering Scales',
    type: 'armour',
    points: 35,
    effect: 'Light armour. Once per turn, you may make your opponent re-roll a single roll To Hit made against the wearer.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Shield of the Warrior True',
    type: 'armour',
    points: 30,
    effect: 'Shield. The bearer has a 5+ Ward save against any wounds suffered during the Shooting phase.',
    phases: ['shooting'],
  },
  {
    name: 'Levitating Shield',
    type: 'armour',
    points: 25,
    effect: 'Infantry only. Shield. The bearer may use it alongside a weapon with the Requires Two Hands special rule during combat.',
    phases: ['combat'],
  },
  {
    name: 'Spellshield',
    type: 'armour',
    points: 25,
    effect: 'Shield. The bearer has a 5+ Ward save against any wounds suffered that were caused by a Magic Missile, a Magical Vortex, or an Assailment spell.',
    phases: ['shooting'],
    subPhases: ['combat'],
  },
  {
    name: 'Armour of Meteoric Iron',
    type: 'armour',
    points: 20,
    effect: 'Gives the wearer an armour value of 5+ which cannot be improved or reduced in any way.',
    phases: ['combat'],
  },
  {
    name: "Trailblazer's Hauberk",
    type: 'armour',
    points: 20,
    effect: 'Infantry only. Heavy armour. The wearer gains Move Through Cover and Scouts special rules.',
    phases: ['movement'],
  },
  {
    name: 'Enchanted Shield',
    type: 'armour',
    points: 10,
    effect: 'Shield. The bearer has a 6+ Ward save against any wounds suffered that were caused by a non-magical enemy attack.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Charmed Shield',
    type: 'armour',
    points: 5,
    effect: 'Shield. Single use. Gives the bearer a 5+ Ward save against a single wound. After use, becomes an ordinary non-magical shield.',
    phases: ['combat', 'shooting'],
  },

  // ─── Talismans ──────────────────────────────────────────────────────
  {
    name: 'Dawnstone',
    type: 'talisman',
    points: 35,
    effect: 'The bearer may re-roll any Armour Save roll of a natural 1.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Icon of Fortitude',
    type: 'talisman',
    points: 35,
    effect: 'Infantry or cavalry only. The bearer is immune to the Multiple Wounds (X) special rule. If wounded by such an attack, they suffer a single wound.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Ironhide Talisman',
    type: 'talisman',
    points: 30,
    effect: 'Infantry only. Any enemy model that makes a successful roll To Hit against the bearer during the Shooting phase or Combat phase must re-roll any rolls To Wound of a natural 6. Does not work against attacks that hit automatically.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Talisman of Protection',
    type: 'talisman',
    points: 30,
    effect: 'Gives the bearer a 5+ Ward save against any wounds suffered.',
    phases: ['combat', 'shooting'],
  },
  {
    name: "Paymaster's Coin",
    type: 'talisman',
    points: 25,
    effect: 'Single use. The bearer can re-roll any failed rolls To Hit made during the Combat phase.',
    phases: ['combat'],
    extremely: true,
  },
  {
    name: 'Obsidian Lodestone',
    type: 'talisman',
    points: 20,
    effect: 'May purchase up to three. One gives Magic Resistance (-1), two gives (-2), three gives (-3).',
    phases: ['strategy'],
    subPhases: ['conjuration'],
    extremely: true,
  },
  {
    name: 'Luckstone',
    type: 'talisman',
    points: 15,
    effect: 'Single use. The bearer can re-roll a single failed Armour Save roll.',
    phases: ['combat', 'shooting'],
    extremely: true,
  },

  // ─── Arcane Items ───────────────────────────────────────────────────
  {
    name: 'Feedback Scroll',
    type: 'arcane-item',
    points: 60,
    effect: 'Single use. May be used instead of a Wizardly dispel attempt. The spell is cast as normal. Once resolved, roll 2D6; for each 4+, the casting Wizard loses a single Wound.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Scroll of Transmogrification',
    type: 'arcane-item',
    points: 50,
    effect: 'Single use. May be used instead of a Wizardly dispel attempt. The spell is cast as normal. The casting player must then roll equal to or lower than the Wizard\'s Level on a D6. If failed, the Wizard turns into a frog (all characteristics except Wounds become 1, cannot cast/dispel/use equipment). Roll D6 each Start of Turn sub-phase; on 4+ the Wizard returns to normal.',
    phases: ['strategy'],
    subPhases: ['conjuration', 'start-of-turn'],
  },
  {
    name: 'Wand of Jet',
    type: 'arcane-item',
    points: 45,
    effect: 'The bearer may apply a +1 modifier to any Casting or Dispel roll. If any natural double is rolled, the Wand is destroyed. Does not negate a natural double 1.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Staff of Quietude',
    type: 'arcane-item',
    points: 35,
    effect: 'During the Command sub-phase, the bearer can attempt a Leadership test. If passed, all Remains in Play spells currently in play are dispelled, including friendly ones.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Lore Familiar',
    type: 'arcane-item',
    points: 30,
    effect: 'The owner does not randomly generate spells. Instead, they may choose which spells they know from their chosen lore (including the signature spell).',
    phases: ['passive'],
  },
  {
    name: 'Scroll of Disruption',
    type: 'arcane-item',
    points: 30,
    effect: 'Once per turn, the bearer may re-roll a Dispel roll. All dice are re-rolled, including any bonus or discard dice.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Tome of Spellcraft',
    type: 'arcane-item',
    points: 30,
    effect: 'Once per turn, the bearer may re-roll a Casting roll. All dice are re-rolled, including any bonus or discard dice.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Dispel Scroll',
    type: 'arcane-item',
    points: 20,
    effect: 'Single use. May be used when attempting a Wizardly dispel. Roll an extra D6 on the Dispel roll and discard the lowest. If double 1 is rolled on any two dice, the Wizard is outclassed.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Power Scroll',
    type: 'arcane-item',
    points: 20,
    effect: 'Single use. May be used when attempting to cast a spell. Roll an extra D6 on the Casting roll and discard the lowest. If double 1 is rolled on any two dice, the spell is miscast.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Arcane Familiar',
    type: 'arcane-item',
    points: 15,
    effect: 'The owner knows spells from two Lores of Magic rather than one. Roll for each Lore separately. May discard one randomly generated spell and replace it with the signature spell of the same Lore.',
    phases: ['passive'],
  },
  {
    name: 'Earthing Rod',
    type: 'arcane-item',
    points: 5,
    effect: 'Single use. If the Wizard miscasts, they may re-roll the result on the Miscast table.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },

  // ─── Enchanted Items ────────────────────────────────────────────────
  {
    name: 'Wizarding Hat',
    type: 'enchanted-item',
    points: 45,
    effect: 'The wearer is a Level 1 Wizard and knows one randomly generated spell from a Lore of Magic of your choosing. The wearer also becomes subject to the Stupidity special rule.',
    phases: ['strategy', 'shooting'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Arch-Lightning Rod',
    type: 'enchanted-item',
    points: 40,
    effect: 'Single use. During the Command sub-phase, if not engaged in combat, the bearer may attempt a Leadership test (unmodified). If passed, until your next Start of Turn sub-phase enemy units cannot use the Fly (X) special rule.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Flying Carpet',
    type: 'enchanted-item',
    points: 40,
    effect: 'Regular infantry or heavy infantry only. The bearer gains Fly (8) and Swiftstride. However, the bearer cannot join a unit.',
    phases: ['movement'],
  },
  {
    name: 'Healing Potion',
    type: 'enchanted-item',
    points: 35,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. The model immediately recovers D3 lost Wounds.',
    phases: ['strategy'],
    subPhases: ['command'],
    extremely: true,
  },
  {
    name: 'Ruby Ring of Ruin',
    type: 'enchanted-item',
    points: 35,
    effect: 'The wielder can cast the Fireball spell from the Lore of Battle Magic as a Bound spell, with a Power Level of 1.',
    phases: ['shooting'],
  },
  {
    name: 'Potion of Fervour',
    type: 'enchanted-item',
    points: 30,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. Until the end of that turn, the model has a +D3 modifier to its Attacks characteristic (max 10).',
    phases: ['strategy', 'combat'],
    subPhases: ['command'],
  },
  {
    name: 'Potion of Strength',
    type: 'enchanted-item',
    points: 25,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. Until the end of that turn, the model has a +D3 modifier to its Strength characteristic (max 10).',
    phases: ['strategy', 'combat'],
    subPhases: ['command'],
    extremely: true,
  },
  {
    name: 'Becalming Orb',
    type: 'enchanted-item',
    points: 20,
    effect: 'Single use. The bearer may cast a Bound spell (Power Level 1): Hex, Casting Value 8+, Range: Self. Until your next Start of Turn sub-phase, enemy Wizards within 15" when attempting to cast must increase that spell\'s casting value by 2.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Potion of Toughness',
    type: 'enchanted-item',
    points: 20,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. Until the end of that turn, the model has a +D3 modifier to its Toughness characteristic (max 10).',
    phases: ['strategy', 'combat', 'shooting'],
    subPhases: ['command'],
    extremely: true,
  },
  {
    name: 'Potion of Speed',
    type: 'enchanted-item',
    points: 10,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. Until the end of that turn, the model has a +D3 modifier to its Initiative characteristic (max 10).',
    phases: ['strategy', 'combat'],
    subPhases: ['command'],
    extremely: true,
  },
  {
    name: 'Potion of Foolhardiness',
    type: 'enchanted-item',
    points: 5,
    effect: 'Single use. During the Command sub-phase, the bearer can consume it. Until the end of that turn, the model gains the Immune To Psychology special rule.',
    phases: ['strategy'],
    subPhases: ['command'],
    extremely: true,
  },

  // ─── Magic Standards (Banners) ──────────────────────────────────────
  {
    name: 'Banner of Iron Resolve',
    type: 'banner',
    points: 50,
    effect: 'The unit gains the Stubborn special rule.',
    phases: ['combat'],
  },
  {
    name: 'Banner of the Steadfast',
    type: 'banner',
    points: 50,
    effect: 'Infantry only. If the unit belongs to the losing side of a Combat, it can Fall Back in Good Order even if the winning side has more than twice its Unit Strength.',
    phases: ['combat'],
  },
  {
    name: 'Totem of Wrath',
    type: 'banner',
    points: 50,
    effect: 'During a turn in which the unit charged, models improve the Armour Piercing characteristic of their weapons by 1, and may re-roll any rolls To Wound of a natural 1.',
    phases: ['combat'],
  },
  {
    name: 'Razor Standard',
    type: 'banner',
    points: 40,
    effect: 'The unit gains the Armour Bane (2) special rule.',
    phases: ['combat'],
  },
  {
    name: 'Banner of Swirling Wind',
    type: 'banner',
    points: 30,
    effect: 'Any enemy model that shoots at the unit suffers an additional -1 To Hit modifier.',
    phases: ['shooting'],
  },
  {
    name: 'Rampaging Banner',
    type: 'banner',
    points: 30,
    effect: 'When the unit declares a charge, it may re-roll its Charge roll.',
    phases: ['movement'],
  },
  {
    name: 'The Blazing Banner',
    type: 'banner',
    points: 25,
    effect: 'The unit gains the Flaming Attacks special rule.',
    phases: ['combat', 'shooting'],
  },
  {
    name: "Monster Hunter's Tapestry",
    type: 'banner',
    points: 25,
    effect: 'Enemy units may not make Stomp Attacks against the unit.',
    phases: ['combat'],
  },
  {
    name: 'War Banner',
    type: 'banner',
    points: 25,
    effect: 'When calculating combat result, the unit may claim an additional +1 combat result point.',
    phases: ['combat'],
  },

  // ─── Dark Elves ──────────────────────────────────────────────────────
  {
    name: 'Executioner\'s Axe',
    type: 'weapon',
    points: 70,
    effect: 'Killing Blow, Magical Attacks, Strike Last. AP -2. When making a roll To Wound, a roll of 2+ is always a success, regardless of the target\'s Toughness.',
    phases: ['combat'],
  },
  {
    name: 'Sword of Ruin',
    type: 'weapon',
    points: 65,
    effect: 'Magical Attacks. No armour, Ward or Regeneration saves are permitted against wounds caused by the Sword of Ruin.',
    phases: ['combat'],
  },
  {
    name: 'Lifetaker',
    type: 'weapon',
    points: 35,
    effect: 'Range 24", S3, AP -1. Armour Bane (1), Magical Attacks, Multiple Shots (D3+1), Poisoned Attacks.',
    phases: ['shooting'],
  },
  {
    name: 'Whip of Agony',
    type: 'weapon',
    points: 30,
    effect: 'S+1, AP -1. Magical Attacks, Strike First. High Beastmasters only. Any enemy model that suffers one or more unsaved wounds suffers a -1 modifier to its Toughness (min 1) for the remainder of the game.',
    phases: ['combat'],
  },
  {
    name: 'Shield of Ghrond',
    type: 'armour',
    points: 40,
    effect: 'Shield. All attacks directed against the bearer suffer a -1 modifier to their Strength (min 1).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Blood Armour',
    type: 'armour',
    points: 30,
    effect: 'Infantry or cavalry only. Armour value of 5+. For each unsaved wound the wearer inflicts, this armour value is improved by 1, to a maximum of 2+.',
    phases: ['combat'],
  },
  {
    name: 'Pendant of Khaeleth',
    type: 'talisman',
    points: 40,
    effect: 'The bearer has a 5+ Ward save against wounds caused by attacks with S4 or lower, and a 4+ Ward save against wounds caused by attacks with S5 or higher.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Pearl of Infinite Bleakness',
    type: 'talisman',
    points: 15,
    effect: 'The bearer and any unit they join gain the Immune to Psychology special rule.',
    phases: ['passive'],
  },
  {
    name: 'Black Staff',
    type: 'arcane-item',
    points: 55,
    effect: 'When the bearer casts a spell, roll an extra D6 on the Casting roll and discard the lowest. If a double 1 is rolled on any two dice, the spell is miscast.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Tome of Furion',
    type: 'arcane-item',
    points: 15,
    effect: 'The bearer knows one more spell (chosen in the usual way) than is normal for their Level of Wizardry.',
    phases: ['passive'],
  },
  {
    name: 'Focus Familiar',
    type: 'arcane-item',
    points: 10,
    effect: 'Single use. When casting a spell, place a marker within 12". The range and effects of the spell are measured from this marker rather than the caster.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Black Dragon Egg',
    type: 'enchanted-item',
    points: 35,
    effect: 'Single use. During the Command sub-phase, the bearer may consume it. Until end of turn, the model has T6 (cannot be further improved) and gains noxious breath (-1 WS, no armour saves permitted).',
    phases: ['strategy', 'combat'],
    subPhases: ['command'],
  },
  {
    name: 'Hydra\'s Tooth',
    type: 'enchanted-item',
    points: 30,
    effect: 'Missile weapon. Range 9", S user, AP -3. Magical Attacks, Move & Shoot, Quick Shot. Can target a specific model within the target unit.',
    phases: ['shooting'],
  },
  {
    name: 'The Guiding Eye',
    type: 'enchanted-item',
    points: 25,
    effect: 'Single use. The bearer and any unit they have joined may re-roll any failed rolls To Hit made during the Shooting phase.',
    phases: ['shooting'],
  },
  {
    name: 'Banner of Nagarythe',
    type: 'banner',
    points: 65,
    effect: 'The unit gains the Stubborn special rule. When calculating combat result, the unit may claim an additional +1 combat result point.',
    phases: ['combat'],
  },
  {
    name: 'Standard of Slaughter',
    type: 'banner',
    points: 40,
    effect: 'When the unit carrying this standard charges into combat, it gains an additional +D3 bonus to its combat result during that turn.',
    phases: ['combat'],
  },
  {
    name: 'Banner of Har Ganeth',
    type: 'banner',
    points: 25,
    effect: 'The unit improves the Armour Piercing characteristic of its combat weapons by 1.',
    phases: ['combat'],
  },
  {
    name: 'Cold-Blooded Banner',
    type: 'banner',
    points: 20,
    effect: 'Single use. When the unit makes any Leadership test, including Break tests, it may roll an additional D6 and discard the highest result.',
    phases: ['combat'],
  },

  // ─── Kingdom of Bretonnia ────────────────────────────────────────────
  {
    name: 'Crusader\'s Lance',
    type: 'weapon',
    points: 60,
    effect: 'S+2, AP -2. Armour Bane (2), Furious Charge, Hatred (all enemies), Magical Attacks. Can only be used during a turn in which the wielder charged; otherwise must use hand weapon. Errantry Crusade only; cavalry or monster only.',
    phases: ['combat'],
  },
  {
    name: 'Frontier Axe',
    type: 'weapon',
    points: 30,
    effect: 'S+2, AP -3. Magical Attacks, Multiple Wounds (2), Requires Two Hands. Bretonnian Exiles only.',
    phases: ['combat'],
  },
  {
    name: 'Sword of the Stout Hearted',
    type: 'weapon',
    points: 25,
    effect: 'S+2, AP -1. Armour Bane (1), Immune to Psychology, Magical Attacks, Requires Two Hands.',
    phases: ['combat'],
  },
  {
    name: 'Foebreaker',
    type: 'weapon',
    points: 20,
    effect: 'S+1. When a target suffers unsaved wounds, it must pass a Toughness test or suffer -1 to WS and Attacks (min 1) until end of next Combat phase.',
    phases: ['combat'],
  },
  {
    name: 'The Dolorous Blade',
    type: 'weapon',
    points: 0,
    effect: 'Two profiles, chosen at start of each combat round. Rapid Strikes: S user, AP -1, Extra Attacks (+D6), Magical Attacks. Deadly Blows: S+2, AP -1, Armour Bane (1), Magical Attacks, Multiple Wounds (2).',
    phases: ['combat'],
  },
  {
    name: 'Sorrow\'s End',
    type: 'weapon',
    points: 0,
    effect: 'S+1, AP -1. Magical Attacks, Monster Slayer, Multiple Wounds (2).',
    phases: ['combat'],
  },
  {
    name: 'Anointed Armour',
    type: 'armour',
    points: 45,
    effect: 'Heavy armour (5+). While the wearer maintains the Blessing of the Lady, they are immune to Killing Blow and Multiple Wounds (X). Grail Vow, infantry or cavalry only.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Ironspike Shield',
    type: 'armour',
    points: 20,
    effect: 'Shield. Whenever an opponent rolls a natural 1 To Hit or To Wound against the wielder in combat, they suffer a S3, AP -1 hit. Bretonnian Exiles only.',
    phases: ['combat'],
  },
  {
    name: 'Dragonhide Cloak',
    type: 'talisman',
    points: 0,
    effect: 'AP of any non-magical weapon attacking the bearer is reduced by 2. Immune to Killing Blow and Multiple Wounds (X). 3+ Ward save against Flaming Attacks.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Grail Pendant',
    type: 'talisman',
    points: 40,
    effect: 'Single use. When the wearer loses their final Wound, roll a D6; on a 2+, that Wound is not lost. Grail Vow only.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Lucky Heirloom',
    type: 'talisman',
    points: 25,
    effect: 'Once per round, the bearer can re-roll a single failed To Hit, To Wound, Armour Save, or Ward Save roll. Bretonnian Exiles only.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Heart of the Wilds',
    type: 'arcane-item',
    points: 40,
    effect: 'The bearer gains +1 to casting rolls while within natural terrain features (woods, difficult terrain, dangerous terrain).',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Diadem of Power',
    type: 'arcane-item',
    points: 35,
    effect: 'When the bearer attempts to cast a Magical Vortex, Magic Missile, or Assailment spell, they gain +1 to their Casting roll. Errantry Crusade only.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Flamestrike Wand',
    type: 'arcane-item',
    points: 15,
    effect: 'Single use. The bearer may cast Fireball from Battle Magic as a bound spell with Power Level 3. Bretonnian Exiles only.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'The Staff of the Elements',
    type: 'arcane-item',
    points: 0,
    effect: 'Lady Elisse may discard two randomly generated spells instead of one, then select two signature spells from Lore of Elementalism and/or Lore of the Lady.',
    phases: ['passive'],
  },
  {
    name: 'The Seal of Parravon',
    type: 'enchanted-item',
    points: 35,
    effect: 'When the bearer makes a roll To Hit, a roll of 3+ is always a success, regardless of the target\'s WS.',
    phases: ['combat'],
  },
  {
    name: 'Crusader\'s Clarion',
    type: 'enchanted-item',
    points: 25,
    effect: 'When the bearer charges, their mount and all mounts in their unit gain +1 Strength for that turn. Must be mounted on a Bretonnian Warhorse. Errantry Crusade only.',
    phases: ['combat'],
  },
  {
    name: 'Wyrmbreath Vial',
    type: 'enchanted-item',
    points: 20,
    effect: 'Single use. Breath weapon with S4, AP -1. Flaming Attacks, Magical Attacks. Bretonnian Exiles only.',
    phases: ['shooting'],
  },
  {
    name: 'Chalice of Brionne',
    type: 'enchanted-item',
    points: 0,
    effect: 'Within the bearer\'s Command range, enemy characters attempting to use special rules or magic items requiring a Leadership test suffer -2 to Ld (min 2).',
    phases: ['passive'],
  },
  {
    name: 'Banner of the Lady\'s Grace',
    type: 'banner',
    points: 75,
    effect: 'The unit ignores all negative modifiers to its Leadership characteristic.',
    phases: ['passive'],
  },
  {
    name: 'Crusader\'s Tapestry',
    type: 'banner',
    points: 40,
    effect: 'The unit gains the Frenzy special rule. Errantry Crusade only.',
    phases: ['combat'],
  },
  {
    name: 'Banner of Honourable Warfare',
    type: 'banner',
    points: 25,
    effect: 'The unit must re-roll any failed To Hit rolls during the first round of combat when engaged with an enemy equipped with missile weapons.',
    phases: ['combat'],
  },
  {
    name: 'Banner of the Zealous Knight',
    type: 'banner',
    points: 25,
    effect: 'The unit gains the Vanguard special rule. Bretonnian Exiles only.',
    phases: ['movement'],
  },

  // ─── Vampire Counts ──────────────────────────────────────────────────
  {
    name: 'Frostblade',
    type: 'weapon',
    points: 60,
    effect: 'Killing Blow, Magical Attacks. When an enemy model takes unsaved wounds, it must pass a Toughness test or gain Strike Last (I reduced to 1) for the remainder of the game.',
    phases: ['combat'],
  },
  {
    name: 'Sword of Kings',
    type: 'weapon',
    points: 55,
    effect: 'S+1, AP -1. Killing Blow on a natural 5 or 6 (rather than only on a 6).',
    phases: ['combat'],
  },
  {
    name: 'Blood Drinker',
    type: 'weapon',
    points: 45,
    effect: 'S user, AP -1. If the wielder causes one or more unsaved wounds during the Combat phase, they recover a single lost Wound.',
    phases: ['combat'],
  },
  {
    name: 'Dreadlance',
    type: 'weapon',
    points: 40,
    effect: 'S+2, AP -2. Armour Bane (1), Magical Attacks. Cavalry or monster only. Only usable during the turn a charge occurs; otherwise must use hand weapon. May re-roll failed To Hit rolls.',
    phases: ['combat'],
  },
  {
    name: 'The Flayed Hauberk',
    type: 'armour',
    points: 35,
    effect: 'Heavy armour that wizards can equip without penalty. The wearer gains a 6+ Ward save.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'The Accursed Armour',
    type: 'armour',
    points: 30,
    effect: 'Infantry or cavalry only. Full plate armour (4+). The wearer gains +1 Toughness but suffers -1 WS and -1 Initiative (min 1).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Von Carstein Ring',
    type: 'talisman',
    points: 40,
    effect: 'Vampires only. Single use. When the wearer loses their last Wound, roll a D6; on a 2+, the Wound is not lost.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Crown of the Damned',
    type: 'talisman',
    points: 35,
    effect: 'The wearer gains a 4+ Ward save. However, the wearer becomes subject to the Stupidity special rule.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Skull Staff',
    type: 'arcane-item',
    points: 50,
    effect: 'Increases Dispel range by 3". When attempting a Wizardly dispel, the bearer may apply a +1 modifier to the Dispel roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Sceptre de Noirot',
    type: 'arcane-item',
    points: 35,
    effect: 'The bearer may use the Invocation of Nehek special rule twice per Command sub-phase instead of once. Each time, roll a D6; on a 1, the bearer suffers a single Wound.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Spell Familiar',
    type: 'arcane-item',
    points: 15,
    effect: 'The bearer knows one additional spell beyond their normal allotment for their Level of Wizardry.',
    phases: ['passive'],
  },
  {
    name: 'Curse of the Revenant',
    type: 'enchanted-item',
    points: 50,
    effect: 'Vampiric Power. The Vampire gains a +1 modifier to its Wounds characteristic.',
    phases: ['passive'],
  },
  {
    name: 'Helm of Commandment',
    type: 'enchanted-item',
    points: 40,
    effect: 'Necromancers and Wights only. During the Command sub-phase, make a Leadership test. If passed, until your next Start of Turn sub-phase, this character and their unit gains +D3 WS (max 10).',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Beguile',
    type: 'enchanted-item',
    points: 40,
    effect: 'Vampiric Power. Enemy units must make a Leadership test before rolling To Hit against this Vampire. If failed, only natural 6s will hit.',
    phases: ['combat'],
  },
  {
    name: 'Flying Horror',
    type: 'enchanted-item',
    points: 35,
    effect: 'Vampiric Power. Infantry only. The Vampire gains Fly (10). Cannot join a unit.',
    phases: ['passive'],
  },
  {
    name: 'Hand of Dust',
    type: 'enchanted-item',
    points: 35,
    effect: 'Necromancers only. Bound spell (Power Level 2, Casting Value 9+, Assailment). Target enemy unit suffers 2D6 S5 hits, AP -1. Each time used, roll a D6; on a 1, the item is destroyed.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Dark Acolyte',
    type: 'enchanted-item',
    points: 30,
    effect: 'Vampiric Power. The Vampire gains Invocation of Nehek and counts as a Level 1 Wizard for using it. During the Command sub-phase, may resurrect fallen Necromantic Undead units within 12".',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Master of the Black Arts',
    type: 'enchanted-item',
    points: 30,
    effect: 'Vampiric Power. Vampire Count (Level 2) or Vampire Thrall (Level 1) only. The Vampire\'s Level of Wizardry increases by 1.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Cloak of Mist & Shadows',
    type: 'enchanted-item',
    points: 30,
    effect: 'Necromancers with infantry troop type only. The wearer gains the Ethereal special rule.',
    phases: ['passive'],
  },
  {
    name: 'Supernatural Horror',
    type: 'enchanted-item',
    points: 20,
    effect: 'Vampiric Power. The Vampire gains the Terror special rule.',
    phases: ['combat'],
  },
  {
    name: 'Lord of the Night',
    type: 'enchanted-item',
    points: 15,
    effect: 'Vampiric Power. During the Command sub-phase, make a Leadership test. If passed, a friendly Fell Bats, Bat Swarms, or Dire Wolves unit within 12" recovers D6 lost Wounds.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Banner of the Barrows',
    type: 'banner',
    points: 65,
    effect: 'Wight Lord BSB only. During the Combat phase, when the unit rolls To Hit, a roll of 3+ is always a success regardless of the target\'s WS.',
    phases: ['combat'],
  },
  {
    name: 'Drakenhof Banner',
    type: 'banner',
    points: 50,
    effect: 'A unit with Regeneration (X+) improves its Regeneration save by 1.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'The Screaming Banner',
    type: 'banner',
    points: 45,
    effect: 'When an enemy unit makes a Leadership test due to Fear caused by this unit, it must roll an extra D6 and discard the lowest result.',
    phases: ['combat'],
  },
  {
    name: 'Standard of Hellish Vigour',
    type: 'banner',
    points: 40,
    effect: 'The unit gains the Reserve Move special rule, allowing movement after the Shooting phase if it did not charge, march, or flee.',
    phases: ['passive'],
  },

  // ─── Lizardmen ───────────────────────────────────────────────────────
  {
    name: 'Blade of Revered Tzunki',
    type: 'weapon',
    points: 65,
    effect: 'S+1. No armour or Ward saves are permitted against wounds caused. Regeneration saves may still be taken.',
    phases: ['combat'],
  },
  {
    name: 'Scimitar of the Sun Resplendent',
    type: 'weapon',
    points: 50,
    effect: 'AP -1. Extra Attacks (+D3), Flaming Attacks, Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Staff of the Lost Sun',
    type: 'weapon',
    points: 40,
    effect: 'Ranged (12"): S4, AP -3, Magical Attacks, Multiple Shots (3). Combat: S+1, Magical Attacks, Requires Two Hands.',
    phases: ['shooting', 'combat'],
  },
  {
    name: 'Piranha Blade',
    type: 'weapon',
    points: 35,
    effect: 'AP -1. Magical Attacks, Multiple Wounds (2).',
    phases: ['combat'],
  },
  {
    name: 'Shield of the Mirror Pool',
    type: 'armour',
    points: 40,
    effect: 'Shield. Whenever the bearer sustains one or more Wounds from a Magic Missile, the caster suffers a single S5, AP -2 hit.',
    phases: ['passive'],
  },
  {
    name: 'Hide of the Cold Ones',
    type: 'armour',
    points: 20,
    effect: 'Improves armour value by 1 (max 2+). Can be worn with other armour. The wearer is subject to the Stupidity special rule.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Glyph Necklace',
    type: 'talisman',
    points: 45,
    effect: 'The bearer has a 5+ Ward save and gains Magic Resistance (-2).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Aura of Quetzl',
    type: 'talisman',
    points: 40,
    effect: 'Any enemy model directing attacks against the bearer during the Combat phase suffers -1 To Hit.',
    phases: ['combat'],
  },
  {
    name: 'Cupped Hands of the Old Ones',
    type: 'arcane-item',
    points: 55,
    effect: 'When the bearer miscasts, roll a D6. On a 1, follow the Miscast table as normal. On a 2+, nominate an enemy character and centre a 3" blast template over them; every model under suffers a single S6, AP -2 hit.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Cube of Darkness',
    type: 'arcane-item',
    points: 50,
    effect: 'Single use. May be used instead of attempting a dispel. The spell is automatically dispelled. All Remains in Play spells are also dispelled, including friendly ones.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Itxi Grub',
    type: 'arcane-item',
    points: 30,
    effect: 'Single use. Before making a Casting roll, the bearer may attempt to consume a grub by making a Toughness test. Success grants +3 to the Casting roll. Failure costs one Wound.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Higher State of Mind',
    type: 'enchanted-item',
    points: 60,
    effect: 'The bearer gains the Ethereal special rule. Can only be wounded by Magical Attacks.',
    phases: ['passive'],
  },
  {
    name: 'Becalming Cogitation',
    type: 'enchanted-item',
    points: 50,
    effect: 'Once per turn, the Slann may re-roll one D6 when making a Wizardly dispel attempt. Increases Dispel range by 3".',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Wandering Deliberations',
    type: 'enchanted-item',
    points: 40,
    effect: 'Instead of generating spells normally, this character knows four signature spells chosen from: Battle Magic, Daemonology, Dark Magic, Elementalism, High Magic, Illusion, and Necromancy. May discard one in favour of a spell from the Lore of Lustria.',
    phases: ['passive'],
  },
  {
    name: 'Cloak of Feathers',
    type: 'enchanted-item',
    points: 40,
    effect: 'Skink Heroes with infantry troop type only. The bearer gains Fly (10) and Swiftstride.',
    phases: ['movement'],
  },
  {
    name: 'Transcendent Healing',
    type: 'enchanted-item',
    points: 35,
    effect: 'The bearer gains the Regeneration (5+) special rule.',
    phases: ['passive'],
  },
  {
    name: 'Sorcerous Void',
    type: 'enchanted-item',
    points: 30,
    effect: 'The bearer gains Magic Resistance (-D3). Roll the D3 before armies are deployed.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Harrowing Scrutiny',
    type: 'enchanted-item',
    points: 20,
    effect: 'The bearer gains the Terror special rule.',
    phases: ['combat'],
  },
  {
    name: 'Venom of the Firefly Frog',
    type: 'enchanted-item',
    points: 15,
    effect: 'All combat attacks by the bearer gain Poisoned Attacks and Flaming Attacks. Only applies to non-magical weapons; does not apply to mount.',
    phases: ['combat'],
  },
  {
    name: 'Horned One',
    type: 'enchanted-item',
    points: 10,
    effect: 'Saurus Heroes on Cold Ones only. The mount loses Stupidity and gains M8.',
    phases: ['passive'],
  },
  {
    name: 'Soul of Stone',
    type: 'enchanted-item',
    points: 10,
    effect: 'When rolling on the Miscast table, the character may modify the result by -1 (min 2) or +1 (max 12).',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Sun Standard of Chotec',
    type: 'banner',
    points: 40,
    effect: 'Enemy units cannot declare Stand & Shoot against this unit. Enemy models targeting the unit in the Shooting phase suffer an additional -1 To Hit.',
    phases: ['shooting', 'combat'],
  },
  {
    name: 'Skavenpelt Banner',
    type: 'banner',
    points: 35,
    effect: 'The unit gains Frenzy and Hatred (Skaven).',
    phases: ['combat'],
  },
  {
    name: 'Totem of Prophecy',
    type: 'banner',
    points: 30,
    effect: 'The unit gains the Fear special rule.',
    phases: ['combat'],
  },
  {
    name: 'Jaguar Standard',
    type: 'banner',
    points: 20,
    effect: 'When making a Pursuit roll, the unit may roll an extra D6 and discard the lowest result.',
    phases: ['combat'],
  },

  // ─── Chaos Dwarfs ────────────────────────────────────────────────────
  {
    name: 'Black Hammer of Hashut',
    type: 'weapon',
    points: 60,
    effect: 'S+2, AP -1. Flaming Attacks, Killing Blow (against Flammable units), Magical Attacks, Multiple Wounds (D3).',
    phases: ['combat'],
  },
  {
    name: 'Dark Maul',
    type: 'weapon',
    points: 50,
    effect: 'Killing Blow, Magical Attacks. When a model takes unsaved wounds, it must pass a Strength test or suffer an additional wound.',
    phases: ['combat'],
  },
  {
    name: 'Dagger of Malice',
    type: 'weapon',
    points: 35,
    effect: 'Frenzy, Hatred (all enemies), Magical Attacks. The wielder cannot lose Frenzy.',
    phases: ['combat'],
  },
  {
    name: 'The Graven Sceptre',
    type: 'weapon',
    points: 30,
    effect: 'S+1. Magical Attacks. When rolling To Wound, a roll of 4+ is always a success regardless of the target\'s Toughness.',
    phases: ['combat'],
  },
  {
    name: 'Armour of Bazherak the Cruel',
    type: 'armour',
    points: 50,
    effect: 'Full plate armour. The wearer gains Immune to Psychology and Magic Resistance (-2).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'The Mask of the Furnace',
    type: 'armour',
    points: 40,
    effect: 'May be worn with other armour. +1 armour value (max 2+) and a 3+ Ward save against wounds caused by Flaming Attacks.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Mantle of Stone',
    type: 'talisman',
    points: 30,
    effect: '+1 Toughness, -1 Initiative.',
    phases: ['passive'],
  },
  {
    name: 'Hellshard',
    type: 'talisman',
    points: 20,
    effect: 'When the bearer is reduced to zero Wounds by an enemy attack during the Combat phase, the attacking unit takes D6 S5, AP -1 hits.',
    phases: ['combat'],
  },
  {
    name: 'Daemon Flask',
    type: 'arcane-item',
    points: 50,
    effect: 'Single use. During the Command sub-phase, all enemy units within this character\'s Command range must make a Panic test.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Vial of Lammasu Blood',
    type: 'arcane-item',
    points: 40,
    effect: 'Single use. May be used instead of attempting a dispel. The spell is automatically dispelled with no Dispel roll required. Cannot dispel perfect invocations.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Scroll of Binding',
    type: 'arcane-item',
    points: 30,
    effect: 'Single use. When casting a spell, roll 3D6 instead of 2D6 for the Casting roll. If a double 1 is rolled on any two dice, the spell is miscast.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Daemonic Familiar',
    type: 'enchanted-item',
    points: 30,
    effect: 'Enemy models engaged in combat with the owner must reduce the armour value of any Ward or Regeneration save by 1 (min 6+).',
    phases: ['combat'],
  },
  {
    name: 'Breath of Hashut',
    type: 'enchanted-item',
    points: 25,
    effect: 'Single use. Breath weapon: S4, AP -2, Flaming Attacks, Magical Attacks.',
    phases: ['shooting'],
  },
  {
    name: 'Obsidian Vambraces',
    type: 'enchanted-item',
    points: 15,
    effect: '+1 Strength, Magic Resistance (-1). If the wearer rolls a natural 1 To Hit during Combat, the gauntlets shatter.',
    phases: ['combat'],
  },
  {
    name: 'The Lammasu\'s Beard',
    type: 'banner',
    points: 65,
    effect: 'The unit gains a 6+ Ward save and Magic Resistance (-2). Friendly units within 6" gain a 5+ Ward save during the Shooting phase and Magic Resistance (-1).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Ashen Banner',
    type: 'banner',
    points: 30,
    effect: 'Enemy models targeting the unit during the Shooting phase suffer an additional -1 To Hit.',
    phases: ['shooting'],
  },
  {
    name: 'Overseer\'s Sigil',
    type: 'banner',
    points: 25,
    effect: 'Friendly units within 9" lose the Levies special rule.',
    phases: ['passive'],
  },
  {
    name: 'Shroud of the Ancestor',
    type: 'banner',
    points: 10,
    effect: 'The unit gains Hatred (Dwarfs).',
    phases: ['combat'],
  },

  // ─── Wood Elves ──────────────────────────────────────────────────────
  {
    name: 'Spear of Twilight',
    type: 'weapon',
    points: 65,
    effect: 'S+2. Killing Blow, Magical Attacks. When rolling To Wound, a roll of 3+ is always a success regardless of the target\'s Toughness.',
    phases: ['combat'],
  },
  {
    name: 'Vaul\'s Wrath',
    type: 'weapon',
    points: 55,
    effect: 'Range 32", S+1, AP -2. Flaming Attacks, Magical Attacks, Multiple Wounds (2). Once per game, if the wielder did not move, may fire as a bolt thrower using Through & Through.',
    phases: ['shooting'],
  },
  {
    name: 'Blades of Loec',
    type: 'weapon',
    points: 45,
    effect: 'Extra Attacks (+D3), Magical Attacks, Requires Two Hands. May re-roll any failed rolls To Wound.',
    phases: ['combat'],
  },
  {
    name: 'Daith\'s Reaper',
    type: 'weapon',
    points: 40,
    effect: 'S+1, AP -1. Enemy models must re-roll any successful Armour Save rolls against wounds caused by this weapon.',
    phases: ['combat'],
  },
  {
    name: 'Bow of Loren',
    type: 'weapon',
    points: 40,
    effect: 'Asrai longbow. Range 32", S, Armour Bane (1), Magical Attacks. May make shooting attacks equal to Attacks characteristic. No modifiers for multiple shots.',
    phases: ['shooting'],
  },
  {
    name: 'Hunt Master\'s Pride',
    type: 'weapon',
    points: 35,
    effect: 'Magical Attacks, Multiple Wounds (2). Multiple Wounds only against monstrous infantry, monstrous cavalry, monstrous creatures, or behemoths. Orion\'s Wild Hunt only.',
    phases: ['combat'],
  },
  {
    name: 'Blades of Endless Flame',
    type: 'weapon',
    points: 25,
    effect: 'S, AP -1. Extra Attacks (+1), Flaming Attacks, Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Asyendi\'s Bane',
    type: 'weapon',
    points: 10,
    effect: 'Asrai longbow. Range 32", S. May re-roll a single failed To Hit roll during the Shooting phase. If the re-roll also fails, the wielder suffers a single S3 hit.',
    phases: ['shooting'],
  },
  {
    name: 'The Spear of Kurnous',
    type: 'weapon',
    points: 0,
    effect: 'Ranged (18"): S+1, AP -2. Combat: S+1, AP -2. Magical Attacks, Multiple Wounds (D3). Ranged shots use Through & Through (S reduced by -1 for each hit after the first).',
    phases: ['shooting', 'combat'],
  },
  {
    name: 'Hawk\'s Talon',
    type: 'weapon',
    points: 0,
    effect: 'Range 30", S, AP -1. Magical Attacks, Multiple Shots (D3+1).',
    phases: ['shooting'],
  },
  {
    name: 'Spear of Talsyn',
    type: 'weapon',
    points: 0,
    effect: 'S, AP -1. Armour Bane (1), Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Helm of the Hunt',
    type: 'armour',
    points: 50,
    effect: 'May be worn with other armour. +1 armour value (max 2+). During any turn the wearer charges, they gain +1 WS and +1 Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Mantle of Rebirth',
    type: 'armour',
    points: 40,
    effect: 'Light armour (6+). The wearer gains Regeneration (5+).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Railarian\'s Mantle',
    type: 'armour',
    points: 35,
    effect: 'Light armour (6+). When within 6" of a woodland terrain feature, the wearer gains a 4+ Ward save.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Cloak of Tumbling Leaves',
    type: 'armour',
    points: 30,
    effect: 'Light armour. The wearer gains Fly (10) and Swiftstride. Cannot join a unit.',
    phases: ['passive'],
  },
  {
    name: 'Glamourweave',
    type: 'talisman',
    points: 30,
    effect: 'Enemy models must make a Leadership test before rolling To Hit against the bearer in the Combat phase. If failed, only natural 6s will hit.',
    phases: ['combat'],
  },
  {
    name: 'Merciw\'s Locus',
    type: 'talisman',
    points: 35,
    effect: 'The bearer\'s Strength cannot be modified by any weapon. However, any model directing attacks against the bearer in Combat also cannot have its Strength modified by any weapon.',
    phases: ['combat'],
  },
  {
    name: 'Ariel\'s Favour',
    type: 'talisman',
    points: 30,
    effect: 'The bearer gains Magic Resistance (-2). Any enemy spell casting roll targeting the bearer\'s unit suffers a -2 modifier.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Orion\'s Favour',
    type: 'talisman',
    points: 25,
    effect: 'Single use. The bearer may re-roll any failed To Hit and/or To Wound rolls during the Combat phase.',
    phases: ['combat'],
  },
  {
    name: 'Cloak of Isha',
    type: 'talisman',
    points: 0,
    effect: '5+ Ward save. During each Start of Turn sub-phase, roll a D6; on a 5+, recover a single lost Wound.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Deepwood Sphere',
    type: 'arcane-item',
    points: 45,
    effect: 'When an enemy Wizard within 6" of a woodland successfully casts a spell, no dispel attempt can be made but after resolution the Wizard suffers D3 S4, AP -1 hits.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Oaken Stave',
    type: 'arcane-item',
    points: 40,
    effect: 'When within 3" of a woodland, Dispel range increases by 3" and when making a Dispel roll, roll an extra D6 and discard the lowest.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Orb of Midsummer',
    type: 'arcane-item',
    points: 35,
    effect: 'Once per turn, the bearer may re-roll a Casting roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Wand of Wych Elm',
    type: 'arcane-item',
    points: 30,
    effect: 'Once per turn, if within 3" of a woodland, the bearer may re-roll a failed Casting roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Sigil of the Mage Queen',
    type: 'arcane-item',
    points: 25,
    effect: 'Single use. The bearer may apply a +2 modifier to a Casting roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Heartwood Pendant',
    type: 'arcane-item',
    points: 15,
    effect: 'The bearer gains access to the Lore of the Wilds as an additional magical lore option.',
    phases: ['passive'],
  },
  {
    name: 'A Blight of Terrors',
    type: 'enchanted-item',
    points: 50,
    effect: 'Spite. This model and any unit it has joined gains the Terror special rule.',
    phases: ['passive'],
  },
  {
    name: 'Wraithstone',
    type: 'enchanted-item',
    points: 50,
    effect: 'Unless fleeing, enemy units within 6" suffer -1 Leadership (min 2).',
    phases: ['passive'],
  },
  {
    name: 'A Muster of Malevolents',
    type: 'enchanted-item',
    points: 40,
    effect: 'Spite. Nobles and Waystalkers only. An enemy model hit by shooting from this model\'s Asrai longbow suffers an additional D3 S2, Armour Bane (1) hits.',
    phases: ['shooting'],
  },
  {
    name: 'Crown of Antlers',
    type: 'enchanted-item',
    points: 35,
    effect: 'The wearer gains Armour Bane (1) and Impact Hits (D3) with AP -2.',
    phases: ['combat'],
  },
  {
    name: 'Hail of Doom Arrow',
    type: 'enchanted-item',
    points: 35,
    effect: 'Single use. Asrai longbow only. If the To Hit roll succeeds, place a small (3") blast template over the target; models underneath suffer S4, AP -1, Magical Attacks hits.',
    phases: ['shooting'],
  },
  {
    name: 'A Befuddlement of Mischiefs',
    type: 'enchanted-item',
    points: 30,
    effect: 'Spite. During Combat, a single enemy unit in base contact suffers -1 WS and -1 Initiative.',
    phases: ['combat'],
  },
  {
    name: 'Moonstone of the Hidden Ways',
    type: 'enchanted-item',
    points: 30,
    effect: 'Single use. May cast Forest Walker (Lore of Athel Loren) as a Bound Spell with Power Level 3. Allows a character in woodland to relocate to a different woodland at least 6" from enemy.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Glamour Weave Kindred',
    type: 'enchanted-item',
    points: 25,
    effect: 'Noble Kindred. Wood Elf Mages only. The character has a 5+ Ward save and gains the Tree Spirit special rule.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'A Murder of Spites',
    type: 'enchanted-item',
    points: 25,
    effect: 'Spite. When this model\'s combat is chosen, a single enemy unit it is engaged with suffers D3 S2, AP -1 hits.',
    phases: ['combat'],
  },
  {
    name: 'A Lamentation of Despairs',
    type: 'enchanted-item',
    points: 20,
    effect: 'Spite. Unless fleeing, enemy units within 6" suffer -1 Leadership when making Fear, Panic, or Terror tests (min 2).',
    phases: ['passive'],
  },
  {
    name: 'Aspect of the Hound',
    type: 'enchanted-item',
    points: 20,
    effect: 'Alter Kindred. The character and their unit may re-roll any To Hit rolls of a natural 1 during the Combat phase.',
    phases: ['combat'],
  },
  {
    name: 'Eternal Kindred',
    type: 'enchanted-item',
    points: 20,
    effect: 'Noble Kindred. Infantry only. The character and their unit may re-roll any To Hit rolls of a natural 1 during the Combat phase.',
    phases: ['combat'],
  },
  {
    name: 'Wailing Arrow',
    type: 'enchanted-item',
    points: 20,
    effect: 'Single use. Asrai longbow only. Any unit that suffers an unsaved wound must make a Panic test as if it had taken heavy casualties.',
    phases: ['shooting'],
  },
  {
    name: 'Wild Rider Kindred',
    type: 'enchanted-item',
    points: 20,
    effect: 'Noble Kindred. Nobles only. Must be mounted on Elven Steed or Great Stag. May only wear light armour. Gains Counter Charge, Frenzy, Furious Charge, and Talismanic Tattoos.',
    phases: ['combat'],
  },
  {
    name: 'Aspect of the Bear',
    type: 'enchanted-item',
    points: 15,
    effect: 'Alter Kindred. Infantry or cavalry only. +1 Strength and +1 Toughness.',
    phases: ['passive'],
  },
  {
    name: 'Blight-Tipped Arrows',
    type: 'enchanted-item',
    points: 15,
    effect: 'Single use. Asrai longbow only. If the target suffers an unsaved wound, it must make a Toughness test each subsequent turn. Failure inflicts an additional wound (no armour or Regeneration saves).',
    phases: ['shooting'],
  },
  {
    name: 'An Annoyance of Netlings',
    type: 'enchanted-item',
    points: 15,
    effect: 'Spite. When the bearer is in a challenge, its opponent suffers -1 To Hit.',
    phases: ['combat'],
  },
  {
    name: 'Scout Kindred',
    type: 'enchanted-item',
    points: 15,
    effect: 'Noble Kindred. Infantry only. The character gains Quick Shot and Scouts.',
    phases: ['passive'],
  },
  {
    name: 'Aspect of the Boar',
    type: 'enchanted-item',
    points: 10,
    effect: 'Alter Kindred. Improves AP of weapons by 1 during a turn in which the character charged. Gains Impact Hits (1).',
    phases: ['combat'],
  },
  {
    name: 'Aspect of the Cat',
    type: 'enchanted-item',
    points: 10,
    effect: 'Alter Kindred. Gains Armour Bane (1) and may re-roll failed To Hit rolls during a challenge.',
    phases: ['combat'],
  },
  {
    name: 'A Resplendence of Luminescents',
    type: 'enchanted-item',
    points: 10,
    effect: 'Spite. This model and its unit gains the Magical Attacks special rule.',
    phases: ['passive'],
  },
  {
    name: 'Horn of the Wild Hunt',
    type: 'enchanted-item',
    points: 0,
    effect: 'Once per game, during the Command sub-phase, Orion may sound this horn. Friendly units within Command range gain Frenzy until end of turn.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Tapestry of Talsyn',
    type: 'banner',
    points: 80,
    effect: 'BSB in Host of Talsyn only. Command Range increases to 18". Friendly units within Command Range gain +1 Leadership (max 10).',
    phases: ['passive'],
  },
  {
    name: 'Banner of the Wildwood',
    type: 'banner',
    points: 40,
    effect: 'The unit gains Fear. If it already has Fear, it instead gains Terror.',
    phases: ['passive'],
  },
  {
    name: 'Banner of the Wild Hunt',
    type: 'banner',
    points: 25,
    effect: 'Orion\'s Wild Hunt only. The unit gains +1 combat result bonus and may re-roll Pursuit rolls.',
    phases: ['combat'],
  },
  {
    name: 'Standard of Morning\'s Chill',
    type: 'banner',
    points: 25,
    effect: 'The bearer can cast Swirling Mists (Lore of the Wilds) as a Bound Spell with Power Level 2. Enemy shooting attacks against the unit must re-roll natural 6s To Hit.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Banner of the Hunter King',
    type: 'banner',
    points: 25,
    effect: 'The unit gains the Vanguard special rule.',
    phases: ['passive'],
  },
  {
    name: 'Banner of the Eternal Queen',
    type: 'banner',
    points: 20,
    effect: 'When within 6" of a woodland, the unit may claim an additional +1 combat result point.',
    phases: ['combat'],
  },
  {
    name: 'Banner of Springtide',
    type: 'banner',
    points: 20,
    effect: 'The unit gains the Quick Shot special rule.',
    phases: ['shooting'],
  },
  {
    name: 'Banner of Midsummer\'s Eve',
    type: 'banner',
    points: 15,
    effect: 'The unit gains the Ignores Cover special rule.',
    phases: ['shooting'],
  },

  // ─── Orcs & Goblins ─────────────────────────────────────────────────
  {
    name: 'Battleaxe of the Last Big Waaagh!',
    type: 'weapon',
    points: 75,
    effect: 'S+2, AP -2. Extra Attacks (+D6), Magical Attacks, Requires Two Hands, Strike Last. If a natural 6 is rolled for Extra Attacks, the weapon loses Extra Attacks at end of the current Combat phase.',
    phases: ['combat'],
  },
  {
    name: 'Bigger, Choppier Axe',
    type: 'weapon',
    points: 55,
    effect: 'S+2, AP -2. Killing Blow, Magical Attacks, Requires Two Hands, Strike Last.',
    phases: ['combat'],
  },
  {
    name: 'Martog\'s Best Basha',
    type: 'weapon',
    points: 50,
    effect: 'S+1, AP -2. Magical Attacks, Requires Two Hands. The wielder gains +1 WS and +1 Initiative.',
    phases: ['combat'],
  },
  {
    name: 'Porko\'s Pigstikka',
    type: 'weapon',
    points: 40,
    effect: 'Cavalry, Monster, or Chariot only. S+1, AP -1. Armour Bane (1), Magical Attacks. S and AP modifiers apply only during a turn the wielder charged. Grants +1 Attack per rank the enemy unit possesses.',
    phases: ['combat'],
  },
  {
    name: 'Da Choppiest Choppa',
    type: 'weapon',
    points: 35,
    effect: 'S+1, AP -3. Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Dagger of Malice',
    type: 'weapon',
    points: 35,
    effect: 'Frenzy, Hatred (all enemies), Magical Attacks. The wielder cannot lose Frenzy.',
    phases: ['combat'],
  },
  {
    name: 'Da Akrit Axe',
    type: 'weapon',
    points: 30,
    effect: 'S+1. Armour Bane (1), Magical Attacks. May re-roll failed To Hit rolls.',
    phases: ['combat'],
  },
  {
    name: 'Backstabber\'s Blade',
    type: 'weapon',
    points: 25,
    effect: 'Goblin and Night Goblin Bosses only. S+1, AP -1. Magical Attacks. May re-roll failed To Wound if engaged with enemy flank; re-roll failed To Hit and To Wound if engaged with rear.',
    phases: ['combat'],
  },
  {
    name: 'Wollopa\'s One Hit Wunda',
    type: 'weapon',
    points: 15,
    effect: 'Goblin and Night Goblin Bosses only. Single use. First round of combat: S10, AP -3, Magical Attacks, Strike First. Otherwise counts as a hand weapon with Magical Attacks.',
    phases: ['combat'],
  },
  {
    name: 'Bog-wood Staff',
    type: 'weapon',
    points: 0,
    effect: 'Ogdruz Swampdigga only. S+2, AP -1. Magical Attacks, Requires Two Hands. For each unsaved Wound inflicted, Ogdruz may recover a lost Wound.',
    phases: ['combat'],
  },
  {
    name: 'Da Skull Smasha',
    type: 'weapon',
    points: 0,
    effect: 'Kiknik only. Choose profile when combat is chosen. Hammer: S+2, AP -1, Armour Bane (2), Magical Attacks. Pick: S, AP -2, Armour Bane (2), Magical Attacks, Multiple Wounds (2).',
    phases: ['combat'],
  },
  {
    name: 'Trollhide Trousers',
    type: 'armour',
    points: 40,
    effect: 'May be worn with other armour. +1 armour value (max 2+). The wearer gains Regeneration (5+).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Dead \'Ard Armour',
    type: 'armour',
    points: 35,
    effect: 'Black Orc and Orc Bosses only (infantry, cavalry, or chariot). Full plate armour. +1 Toughness.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Armour of Mork',
    type: 'armour',
    points: 30,
    effect: 'Heavy armour (5+). The wearer gains Magic Resistance (-2).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Spiteful Shield',
    type: 'armour',
    points: 20,
    effect: 'Shield. Whenever an enemy rolls a natural 1 To Hit or To Wound against the wielder in combat, that model suffers a S4 hit.',
    phases: ['combat'],
  },
  {
    name: 'Necklace of Blessed Teef',
    type: 'enchanted-item',
    points: 50,
    effect: 'The bearer may re-roll any Armour Save, Ward Save, or Regeneration Save roll of a natural 1.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Sparkly Wizard Finda',
    type: 'talisman',
    points: 45,
    effect: 'The bearer gains Magic Resistance (-2) and Hatred (enemy Wizards).',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'Effigy of Mork',
    type: 'talisman',
    points: 35,
    effect: 'Any model directing attacks against the bearer in Combat suffers -1 To Hit.',
    phases: ['combat'],
  },
  {
    name: 'Glowy Green Amulet',
    type: 'talisman',
    points: 35,
    effect: 'When the bearer\'s unit is targeted by an enemy spell, may use instead of a Wizardly dispel. Roll a D6; on 2+ the spell is dispelled. On 1, the amulet explodes (destroyed, bearer loses a Wound).',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Mantle of Stone',
    type: 'talisman',
    points: 30,
    effect: '+1 Toughness, -1 Initiative.',
    phases: ['passive'],
  },
  {
    name: 'The Collar of Zorga',
    type: 'talisman',
    points: 20,
    effect: 'Enemy beasts of burden (mounts, beasts drawing chariots) directing attacks against the bearer or their unit suffer -1 To Hit in Combat.',
    phases: ['combat'],
  },
  {
    name: 'Staff of Baduumm',
    type: 'arcane-item',
    points: 55,
    effect: 'The bearer gains +D3 to any Casting roll. If a natural double 1 or double 6 is rolled, centre a 5" blast template over the bearer; all models underneath suffer S6, AP -1 hits. The staff is then destroyed.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Idol of Gork',
    type: 'arcane-item',
    points: 40,
    effect: 'The bearer increases spell range by 3". Once per turn, may re-roll a Casting roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Glittering Wotnots',
    type: 'arcane-item',
    points: 40,
    effect: 'When targeted by an enemy spell, may use instead of a Wizardly dispel. Roll a D6: on 1-3, no effect; on 4+, the spell reflects back to the caster who may attempt a Wizardly dispel.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Buzgob\'s Knobbly Staff',
    type: 'arcane-item',
    points: 35,
    effect: 'Once per turn, the bearer may re-roll a Casting roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Idol of Mork',
    type: 'arcane-item',
    points: 30,
    effect: 'Dispel range increases by 3". Once per turn, when attempting a Wizardly dispel, the bearer may re-roll the Dispel roll.',
    phases: ['strategy'],
    subPhases: ['conjuration'],
  },
  {
    name: 'Da Hag\'s Brew',
    type: 'arcane-item',
    points: 25,
    effect: 'Orc, Goblin, and Night Goblin Shamans only. The bearer may also select spells from the Lore of Troll Magic.',
    phases: ['passive'],
  },
  {
    name: 'Big Boss \'At',
    type: 'enchanted-item',
    points: 50,
    effect: 'During the Command sub-phase, if not engaged in combat, make a Leadership test. If passed, the character and their unit gains Unbreakable until the next Start of Turn sub-phase.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Grisly Trophy Rack',
    type: 'enchanted-item',
    points: 30,
    effect: 'Black Orc, Orc, Goblin, and Night Goblin Bosses only. All enemy units within 6" suffer -1 Leadership (min 2).',
    phases: ['passive'],
  },
  {
    name: 'Da Thinkin\' Orc\'s \'At',
    type: 'enchanted-item',
    points: 25,
    effect: '+1 Initiative. The wearer and their unit are not subject to the Impetuous special rule.',
    phases: ['passive'],
  },
  {
    name: '\'Eadbuttin\' \'At',
    type: 'enchanted-item',
    points: 15,
    effect: 'The wearer gains Impact Hits (1) with AP -2.',
    phases: ['combat'],
  },
  {
    name: 'Fungus Wine',
    type: 'enchanted-item',
    points: 10,
    effect: 'Night Goblin characters only. Single use. During the Command sub-phase, make a Leadership test. If passed, the character and their unit gain Immune to Psychology until the next Start of Turn sub-phase.',
    phases: ['strategy'],
    subPhases: ['command'],
  },
  {
    name: 'Da Boss\' Trophy Rack',
    type: 'enchanted-item',
    points: 0,
    effect: 'Kiknik only. During a turn in which he charged, Kiknik and any Goblin Wolf Rider Mob he has joined cause Fear and gain +1 combat result point.',
    phases: ['combat'],
  },
  {
    name: 'Trollhide Shawl',
    type: 'talisman',
    points: 0,
    effect: 'Ogdruz Swampdigga only. +1 armour value. The bearer gains Regeneration (5+) and Flammable.',
    phases: ['combat', 'shooting'],
  },
  {
    name: 'The Big Red Raggedy Flag',
    type: 'banner',
    points: 50,
    effect: 'The unit gains +1 WS (max 10). When calculating combat result, may claim an additional +1 combat result point.',
    phases: ['combat'],
  },
  {
    name: 'Waaagh! Banner',
    type: 'banner',
    points: 40,
    effect: 'The unit increases maximum charge range by 3" and may apply a +D3 modifier to its charge roll.',
    phases: ['combat'],
  },
  {
    name: 'Da Banner of Butchery',
    type: 'banner',
    points: 35,
    effect: 'All models in the unit gain +1 Strength during a turn in which they charged.',
    phases: ['combat'],
  },
  {
    name: 'Da Spider Banner',
    type: 'banner',
    points: 35,
    effect: 'The unit gains Poisoned Attacks. If it already has Poisoned Attacks, attacks wound automatically on a natural 5 or 6 To Hit.',
    phases: ['combat'],
  },
  {
    name: 'Da Angry Ladz Flag',
    type: 'banner',
    points: 35,
    effect: 'The unit gains the Frenzy special rule.',
    phases: ['combat'],
  },
  {
    name: 'Da Banner of Da Nomadz',
    type: 'banner',
    points: 25,
    effect: 'When making a Charge, Flee, or Pursuit roll, the unit may re-roll any dice showing a natural 1.',
    phases: ['combat'],
  },
  {
    name: 'Guff\'s Windy Banner',
    type: 'banner',
    points: 20,
    effect: 'The unit may re-roll any failed Panic test.',
    phases: ['passive'],
  },
  {
    name: 'Banner of the Wildz',
    type: 'banner',
    points: 20,
    effect: 'The unit gains the Move Through Cover special rule.',
    phases: ['passive'],
  },
]

/**
 * Look up a magic item by name (case-insensitive).
 */
export function findMagicItem(name) {
  const lower = name.toLowerCase()
  return MAGIC_ITEMS.find((item) => item.name.toLowerCase() === lower) ?? null
}

/**
 * Return all magic items relevant to a given phase ID.
 */
export function itemsForPhase(phaseId) {
  return MAGIC_ITEMS.filter((item) => item.phases.includes(phaseId))
}

/**
 * Return all magic items of a given type.
 */
export function itemsByType(type) {
  return MAGIC_ITEMS.filter((item) => item.type === type)
}
